---
# Linux: verificar uso de disco y limpiar temporales
- name: Revisar uso de disco
  ansible.builtin.command: df -h
  register: disco
  changed_when: false
  when: ansible_os_family == "Debian"

- name: Mostrar uso de disco
  ansible.builtin.debug:
    var: disco.stdout_lines

- name: Limpiar temporales en Linux
  ansible.builtin.file:
    path: /tmp
    state: absent
  when: ansible_os_family == "Debian"

# Windows: limpiar archivos temporales
- name: Limpiar archivos temporales en Windows
  ansible.windows.win_file:
    path: "C:\\Windows\\Temp"
    state: absent
  when: ansible_os_family == "Windows"
