---
# Linux - tareas automáticas
- name: Crear tarea programada para limpieza semanal
  ansible.builtin.cron:
    name: "limpieza_temp"
    minute: "0"
    hour: "2"
    weekday: "0"
    job: "rm -rf /tmp/*"
  when: ansible_os_family == "Debian"

# Windows - tareas automáticas
- name: Programar limpieza semanal en Windows
  ansible.windows.win_scheduled_task:
    name: "LimpiezaTemporal"
    actions:
      - path: "powershell.exe"
        arguments: "-Command Remove-Item 'C:\\Windows\\Temp\\*' -Recurse -Force"
    triggers:
      - schedule: weekly
        days_of_week: Sunday
        start_boundary: '2025-01-01T02:00:00'
    state: present
  when: ansible_os_family == "Windows"
